openapi: 3.0.0
info:
  title: E-commerce Product Management API
  description: |
    This comprehensive API allows you to manage products in an online store. 

    **Key features include:**
    - Create, read, update, and delete products
    - Manage inventory levels and stock notifications
    - Upload and manage product images
    - Handle customer reviews and ratings
    - Track price history and apply discounts

    All endpoints require authentication via Bearer token. Rate limits apply: 
    1000 requests per hour for standard accounts, 10000 for premium accounts.
  version: 2.3.0
  contact:
    name: API Support Team
    email: apisupport@example.com
    url: https://docs.example.com

servers:
  - url: https://api.example.com/v2
    description: Production server - use for live traffic
  - url: https://staging-api.example.com/v2
    description: Staging environment - safe for testing

tags:
  - name: Products
    description: Everything related to product catalog management
  - name: Inventory
    description: Stock levels, warehouses, and availability tracking
  - name: Reviews
    description: Customer feedback and product ratings
  - name: Media
    description: Image and video uploads for products

paths:
  /products:
    get:
      summary: List all products in the catalog
      description: |
        Retrieves a paginated list of products. This endpoint supports advanced filtering 
        by multiple criteria including price range, categories, brands, and availability status.

        **Performance notes:**
        - Results are cached for 5 minutes
        - Maximum 100 items per page
        - Use the `fields` parameter to reduce response size

        **Sorting options:**
        You can sort by: price (asc/desc), name, created_at, popularity, rating
      operationId: listProducts
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Page number for pagination, starting from 1. Use with the `limit` parameter to navigate through results.
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
            example: 2
        - name: limit
          in: query
          description: |
            Number of products to return per page. 

            **Limits:**
            - Minimum: 1
            - Maximum: 100
            - Default: 20
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: category
          in: query
          description: Filter products by category slug or ID. Supports multiple categories separated by commas.
          required: false
          schema:
            type: string
            example: "electronics,smartphones"
        - name: min_price
          in: query
          description: Minimum price in USD. Only products with price >= this value will be returned.
          required: false
          schema:
            type: number
            format: float
            minimum: 0
            example: 29.99
        - name: max_price
          in: query
          description: Maximum price in USD. Only products with price <= this value will be returned.
          required: false
          schema:
            type: number
            format: float
            minimum: 0
            example: 999.99
        - name: in_stock
          in: query
          description: |
            Filter by availability status:
            - `true`: Only show products currently in stock
            - `false`: Only show out-of-stock products
            - Not specified: Show all products regardless of stock
          required: false
          schema:
            type: boolean
        - name: sort
          in: query
          description: |
            Sort order for results. Format: `field:direction`

            Available fields: price, name, created_at, popularity, rating
            Direction: asc (ascending) or desc (descending)
          required: false
          schema:
            type: string
            default: "created_at:desc"
            example: "price:asc"
        - name: search
          in: query
          description: Full-text search across product name, description, and tags. Supports partial matching and fuzzy search.
          required: false
          schema:
            type: string
            example: "wireless headphones"
      responses:
        "200":
          description: Successfully retrieved the list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: Array of product objects matching the query criteria
                    items:
                      $ref: "#/components/schemas/Product"
                  pagination:
                    type: object
                    description: Pagination metadata for navigating through results
                    properties:
                      current_page:
                        type: integer
                        description: Current page number
                        example: 1
                      total_pages:
                        type: integer
                        description: Total number of pages available
                        example: 45
                      total_items:
                        type: integer
                        description: Total number of products matching the filters
                        example: 892
                      per_page:
                        type: integer
                        description: Number of items per page
                        example: 20
        "400":
          description: Invalid request parameters. Check the error message for details about which parameter is incorrect.
        "401":
          description: Authentication failed. Your API key is missing or invalid.
        "429":
          description: Rate limit exceeded. You have made too many requests in a short period. Please wait before retrying.

    post:
      summary: Create a new product
      description: |
        Creates a new product in the catalog. This is a multi-step process:

        1. **Create the product** with basic information (this endpoint)
        2. Upload product images using the `/products/{id}/images` endpoint
        3. Set inventory levels using the `/products/{id}/inventory` endpoint
        4. Publish the product by updating its status to "active"

        **Important notes:**
        - Products are created in "draft" status by default
        - SKU must be unique across your entire catalog
        - Price must be greater than zero
        - At least one category is required
      operationId: createProduct
      tags:
        - Products
      requestBody:
        required: true
        description: Product details to create the new item in your catalog
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Product successfully created. Use the returned ID to upload images and manage inventory.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Validation error. One or more required fields are missing or contain invalid data.
        "401":
          description: Unauthorized. Please provide a valid API key in the Authorization header.
        "409":
          description: Conflict. A product with this SKU already exists in your catalog.

  /products/{productId}:
    get:
      summary: Get detailed information about a specific product
      description: |
        Retrieves complete details for a single product including:
        - Basic information (name, description, price)
        - All associated images and media
        - Current inventory levels across all warehouses
        - Customer reviews and ratings
        - Price history and active discounts
        - Related products and recommendations
      operationId: getProduct
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: The unique identifier (UUID or SKU) of the product you want to retrieve
          schema:
            type: string
            example: "prod_a1b2c3d4e5"
        - name: include
          in: query
          description: |
            Comma-separated list of related resources to include in the response.

            Available options:
            - `images`: Product photos and media
            - `reviews`: Customer reviews and ratings
            - `inventory`: Stock levels by warehouse
            - `related`: Similar or frequently bought together products
          required: false
          schema:
            type: string
            example: "images,reviews,inventory"
      responses:
        "200":
          description: Product details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found. The specified ID does not exist in the catalog.
        "401":
          description: Authentication required. Please provide valid credentials.

    put:
      summary: Update an existing product
      description: |
        Updates one or more fields of an existing product. Only the fields you include 
        in the request will be updated; all other fields remain unchanged (partial update).

        **What you can update:**
        - Product name and description
        - Pricing and currency
        - Categories and tags
        - Status (draft, active, archived)
        - SEO metadata

        **What you cannot update:**
        - Product ID or SKU (immutable)
        - Creation date
        - Historical sales data
      operationId: updateProduct
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: The unique identifier of the product to update
          schema:
            type: string
      requestBody:
        required: true
        description: Fields to update. Only include the fields you want to change.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Invalid input data. Check the error message for specific validation failures.
        "404":
          description: Product not found
        "409":
          description: Update conflict. The SKU you're trying to use is already taken by another product.

    delete:
      summary: Delete a product from the catalog
      description: |
        Permanently removes a product from your catalog. This action cannot be undone.

        **Important warnings:**
        - All associated images and media will also be deleted
        - Historical order data will remain intact but reference a deleted product
        - Active carts containing this product will be automatically updated
        - You cannot delete products that are part of active orders

        **Best practice:** Consider archiving products instead of deleting them to preserve historical data.
      operationId: deleteProduct
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: The unique identifier of the product to permanently delete
          schema:
            type: string
      responses:
        "204":
          description: Product deleted successfully. No content returned.
        "404":
          description: Product not found. It may have already been deleted.
        "409":
          description: Cannot delete product. It is referenced in active orders or pending shipments.

  /products/{productId}/reviews:
    get:
      summary: Get all customer reviews for a product
      description: |
        Retrieves all customer reviews and ratings for a specific product. 
        Reviews are sorted by helpfulness (most helpful first) by default.

        **Filtering options:**
        - Filter by star rating (1-5 stars)
        - Filter by verified purchase only
        - Filter by date range
        - Include/exclude reviews with photos
      operationId: getProductReviews
      tags:
        - Reviews
      parameters:
        - name: productId
          in: path
          required: true
          description: Product ID to fetch reviews for
          schema:
            type: string
        - name: min_rating
          in: query
          description: Minimum star rating (1-5). Only show reviews with this rating or higher.
          schema:
            type: integer
            minimum: 1
            maximum: 5
        - name: verified_only
          in: query
          description: If true, only show reviews from customers who actually purchased this product
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: Reviews retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    description: Array of customer reviews
                    items:
                      $ref: "#/components/schemas/Review"
                  summary:
                    type: object
                    description: Aggregate statistics about all reviews
                    properties:
                      average_rating:
                        type: number
                        description: Average star rating across all reviews
                        example: 4.3
                      total_reviews:
                        type: integer
                        description: Total number of reviews
                        example: 127
                      rating_distribution:
                        type: object
                        description: Count of reviews by star rating
                        properties:
                          five_star:
                            type: integer
                            example: 85
                          four_star:
                            type: integer
                            example: 25
                          three_star:
                            type: integer
                            example: 10
                          two_star:
                            type: integer
                            example: 5
                          one_star:
                            type: integer
                            example: 2

components:
  schemas:
    Product:
      type: object
      description: Complete product information including metadata and relationships
      properties:
        id:
          type: string
          description: Unique product identifier (UUID format)
          example: "prod_a1b2c3d4e5"
        sku:
          type: string
          description: Stock Keeping Unit - unique product code for inventory management
          example: "WIDGET-001-BLU"
        name:
          type: string
          description: Display name of the product
          example: "Wireless Bluetooth Headphones"
        description:
          type: string
          description: Detailed product description supporting markdown formatting
          example: "Premium over-ear headphones with active noise cancellation and 30-hour battery life"
        price:
          type: number
          format: float
          description: Current selling price in USD
          example: 199.99
        currency:
          type: string
          description: ISO 4217 currency code
          example: "USD"
        stock_quantity:
          type: integer
          description: Total units available across all warehouses
          example: 450
        status:
          type: string
          enum: [draft, active, archived, out_of_stock]
          description: |
            Current product status:
            - draft: Not yet published, visible only to admins
            - active: Live and available for purchase
            - archived: No longer for sale but kept for historical records
            - out_of_stock: Temporarily unavailable
        created_at:
          type: string
          format: date-time
          description: Timestamp when the product was first created
          example: "2024-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp of the most recent update to this product
          example: "2024-02-10T14:22:00Z"

    ProductInput:
      type: object
      description: Data required to create or update a product
      required:
        - name
        - price
        - sku
      properties:
        name:
          type: string
          description: Product name (2-200 characters)
          minLength: 2
          maxLength: 200
        description:
          type: string
          description: Detailed description (markdown supported, max 5000 characters)
          maxLength: 5000
        sku:
          type: string
          description: Unique SKU for inventory tracking
          pattern: "^[A-Z0-9-]+$"
        price:
          type: number
          format: float
          minimum: 0.01
          description: Price must be greater than zero

    Review:
      type: object
      description: Customer review with rating and optional comments
      properties:
        id:
          type: string
          description: Unique review identifier
        rating:
          type: integer
          minimum: 1
          maximum: 5
          description: Star rating from 1 (poor) to 5 (excellent)
        title:
          type: string
          description: Short review headline
          example: "Great sound quality!"
        comment:
          type: string
          description: Detailed review text from the customer
        author_name:
          type: string
          description: Name of the reviewer
        verified_purchase:
          type: boolean
          description: True if the reviewer actually bought this product
        helpful_count:
          type: integer
          description: Number of users who found this review helpful
        created_at:
          type: string
          format: date-time
          description: When the review was submitted
